# Generated by Django 3.1.12 on 2025-08-12 07:50

import attendance_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_type',
            field=models.CharField(choices=[('IN', 'In Time'), ('LUNCH_IN', 'Lunch In'), ('LUNCH_OUT', 'Lunch Out'), ('OUT', 'Out Time')], default='IN', max_length=10),
        ),
    ]
