# Generated by Django 3.1.12 on 2025-08-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_auto_20250812_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_type',
            field=models.CharField(choices=[('IN', 'In Time'), ('OUT', 'Out Time')], default='IN', max_length=10),
        ),
    ]
